### PR TITLE
Define empty list to prevent 'argument of type 'StrictUndefined' is n…

### PR DESCRIPTION
**Pull request by brtknr**
…ot iterable' error

### CODE REVIEW

**Comment by markgoddard** [comment]
When would these not be defined?

**Comment by oneswig** [comment]
Is this for when (eg) attaching clients to a pre-deployed BeeGFS cluster, or building a BeeGFS cluster without clients defined?

**Comment by brtknr** [comment]
When a group is either just a server or a client group

**Comment by brtknr** [comment]
> Is this for when (eg) attaching clients to a pre-deployed BeeGFS cluster, or building a BeeGFS cluster without clients defined?

Precisely

**Pull request merged**
